# Script to build standalone app.R from package files
# This is run by GitHub Actions before shinylive export

# Create app directory if it doesn't exist
if (!dir.exists("app")) {
  dir.create("app")
}

# Read the source files
ui_code <- readLines("R/ui.R")
server_code <- readLines("R/server.R")

# Remove the @noRd roxygen comments and function wrappers
ui_code <- ui_code[!grepl("^#'", ui_code)]
server_code <- server_code[!grepl("^#'", server_code)]

# Find where the actual function definitions start
ui_start <- which(grepl("^ui <- function\\(\\)", ui_code))[1]
server_start <- which(grepl(
  "^server <- function\\(input, output, session\\)",
  server_code
))[1]

# Extract just the function definitions
ui_func <- ui_code[ui_start:length(ui_code)]
server_func <- server_code[server_start:length(server_code)]

# Create the combined app.R
app_content <- c(
  "# This file is auto-generated by build_app.R",
  "# Do not edit manually - edit R/ui.R and R/server.R instead",
  "",
  "library(shiny)",
  "library(bslib)",
  "library(DT)",
  "library(glue)",
  "",
  "# UI",
  ui_func,
  "",
  "# Server",
  server_func,
  "",
  "# Run app",
  "shinyApp(ui = ui(), server = server)"
)

# Write to app directory
writeLines(app_content, "app/app.R")

cat("✓ Created app/app.R from R/ui.R and R/server.R\n")
